DISTRICTS = [
    "Bagalkote",
    "Ballari",
    "Belagavi",
    "Bengaluru Rural",
    "Bengaluru Urban",
    "Bidar",
    "Chamarajanagar",
    "Chikkaballapur",
    "Chikkamagaluru",
    "Chitradurga",
    "Dakshina Kannada",
    "Davanagere",
    "Dharwad",
    "Gadag",
    "Hassan",
    "Haveri",
    "Kalaburagi",
    "Kodagu",
    "Kolar",
    "Koppal",
    "Mandya",
    "Mysuru",
    "Raichur",
    "Ramanagara",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Uttara Kannada",
    "Vijayapura",
    "Vijayanagara",
    "Yadgir"
]

CRIME_TYPES = [
    "Theft",
    "Robbery",
    "Burglary",
    "Murder",
    "Attempt to Murder",
    "Kidnapping",
    "Missing Person",
    "Cyber Crime",
    "Online Fraud",
    "Domestic Violence",
    "Dowry Harassment",
    "Assault",
    "Hit and Run",
    "Road Accident",
    "Drug Trafficking",
    "Illegal Gambling",
    "Extortion",
    "Chain Snatching",
    "Vehicle Theft",
    "ATM Fraud",
    "Cheque Bounce",
    "Land Dispute",
    "Sexual Harassment",
    "Rape",
    "Child Abuse",
    "Human Trafficking",
    "Forgery",
    "Financial Fraud",
    "Rioting",
    "Arson"
]

CASE_STATUS = [
    "Under Investigation",
    "Chargesheet Filed",
    "Solved",
    "Pending",
    "Closed",
    "Transferred",
    "Reopened"
]

OFFICER_NAMES = [
    "Inspector Ramesh",
    "Inspector Prakash",
    "Inspector Ravi",
    "Inspector Suresh",
    "Inspector Mahesh",
    "Inspector Manjunath",
    "Inspector Sunil",
    "Inspector Naveen",
    "Inspector Shankar",
    "Inspector Deepak",
    "PSI Anitha",
    "PSI Kavya",
    "PSI Shwetha",
    "PSI Nandini",
    "PSI Meghana",
    "PSI Harish",
    "PSI Vinay",
    "PSI Kiran",
    "PSI Darshan",
    "PSI Pooja"
]
